import { Permission } from "react-native-health-connect";

export const permissionsToRequest: Permission[] = [
  { accessType: "read", recordType: "Weight" },
  { accessType: "write", recordType: "Weight" },
  { accessType: "read", recordType: "Height" },
  { accessType: "write", recordType: "Height" },
  { accessType: "read", recordType: "HeartRate" },
  { accessType: "write", recordType: "HeartRate" },
  { accessType: "read", recordType: "Steps" },
  { accessType: "write", recordType: "Steps" },
  { accessType: "read", recordType: "Distance" },
  { accessType: "write", recordType: "Distance" },
  { accessType: "read", recordType: "TotalCaloriesBurned" },
  { accessType: "write", recordType: "TotalCaloriesBurned" },
  { accessType: "read", recordType: "RespiratoryRate" },
  { accessType: "write", recordType: "RespiratoryRate" },
  { accessType: "read", recordType: "BloodPressure" },
  { accessType: "write", recordType: "BloodPressure" },
  { accessType: "read", recordType: "BloodGlucose" },
  { accessType: "write", recordType: "BloodGlucose" },
  { accessType: "read", recordType: "OxygenSaturation" },
  { accessType: "write", recordType: "OxygenSaturation" },
  { accessType: "read", recordType: "BodyTemperature" },
  { accessType: "write", recordType: "BodyTemperature" },
];

export const BMI_PERMISSIONS: Permission[] = [
  { accessType: "read", recordType: "Height" },
  { accessType: "write", recordType: "Height" },
  { accessType: "read", recordType: "Weight" },
  { accessType: "write", recordType: "Weight" },
];

export const BLOOD_PRESSURE_PERMISSIONS: Permission[] = [
  { accessType: "read", recordType: "BloodPressure" },
  { accessType: "write", recordType: "BloodPressure" },
];

export const HEART_RATE_PERMISSIONS: Permission[] = [
  { accessType: "read", recordType: "HeartRate" },
  { accessType: "write", recordType: "HeartRate" },
];

export const RESPIRATORY_RATE_PERMISSIONS: Permission[] = [
  { accessType: "read", recordType: "RespiratoryRate" },
  { accessType: "write", recordType: "RespiratoryRate" },
];

export const ACTIVITY_PERMISSIONS: Permission[] = [
  { accessType: "read", recordType: "Steps" },
  { accessType: "write", recordType: "Steps" },
  { accessType: "read", recordType: "Distance" },
  { accessType: "write", recordType: "Distance" },
  { accessType: "read", recordType: "TotalCaloriesBurned" },
  { accessType: "write", recordType: "TotalCaloriesBurned" },
];

export const allPermissions: Permission[] = [
  { accessType: "read", recordType: "ActiveCaloriesBurned" },
  { accessType: "write", recordType: "ActiveCaloriesBurned" },
  { accessType: "read", recordType: "BasalBodyTemperature" },
  { accessType: "write", recordType: "BasalBodyTemperature" },
  { accessType: "read", recordType: "BasalMetabolicRate" },
  { accessType: "write", recordType: "BasalMetabolicRate" },
  { accessType: "read", recordType: "BloodGlucose" },
  { accessType: "write", recordType: "BloodGlucose" },
  { accessType: "read", recordType: "BloodPressure" },
  { accessType: "write", recordType: "BloodPressure" },
  { accessType: "read", recordType: "BodyFat" },
  { accessType: "write", recordType: "BodyFat" },
  { accessType: "read", recordType: "BodyTemperature" },
  { accessType: "write", recordType: "BodyTemperature" },
  { accessType: "read", recordType: "BoneMass" },
  { accessType: "write", recordType: "BoneMass" },
  { accessType: "read", recordType: "CervicalMucus" },
  { accessType: "write", recordType: "CervicalMucus" },
  { accessType: "read", recordType: "Distance" },
  { accessType: "write", recordType: "Distance" },
  { accessType: "read", recordType: "ElevationGained" },
  { accessType: "write", recordType: "ElevationGained" },
  { accessType: "read", recordType: "ExerciseSession" },
  { accessType: "write", recordType: "ExerciseSession" },
  { accessType: "read", recordType: "FloorsClimbed" },
  { accessType: "write", recordType: "FloorsClimbed" },
  { accessType: "read", recordType: "HeartRate" },
  { accessType: "write", recordType: "HeartRate" },
  { accessType: "read", recordType: "Height" },
  { accessType: "write", recordType: "Height" },
  { accessType: "read", recordType: "Hydration" },
  { accessType: "write", recordType: "Hydration" },
  { accessType: "read", recordType: "LeanBodyMass" },
  { accessType: "write", recordType: "LeanBodyMass" },
  { accessType: "read", recordType: "MenstruationFlow" },
  { accessType: "write", recordType: "MenstruationFlow" },
  { accessType: "read", recordType: "MenstruationPeriod" },
  { accessType: "write", recordType: "MenstruationPeriod" },
  { accessType: "read", recordType: "Nutrition" },
  { accessType: "write", recordType: "Nutrition" },
  { accessType: "read", recordType: "OvulationTest" },
  { accessType: "write", recordType: "OvulationTest" },
  { accessType: "read", recordType: "OxygenSaturation" },
  { accessType: "write", recordType: "OxygenSaturation" },
  { accessType: "read", recordType: "Power" },
  { accessType: "write", recordType: "Power" },
  { accessType: "read", recordType: "RespiratoryRate" },
  { accessType: "write", recordType: "RespiratoryRate" },
  { accessType: "read", recordType: "RestingHeartRate" },
  { accessType: "write", recordType: "RestingHeartRate" },
  { accessType: "read", recordType: "SexualActivity" },
  { accessType: "write", recordType: "SexualActivity" },
  { accessType: "read", recordType: "SleepSession" },
  { accessType: "write", recordType: "SleepSession" },
  { accessType: "read", recordType: "Speed" },
  { accessType: "write", recordType: "Speed" },
  { accessType: "read", recordType: "Steps" },
  { accessType: "write", recordType: "Steps" },
  { accessType: "read", recordType: "TotalCaloriesBurned" },
  { accessType: "write", recordType: "TotalCaloriesBurned" },
  { accessType: "read", recordType: "Vo2Max" },
  { accessType: "write", recordType: "Vo2Max" },
  { accessType: "read", recordType: "Weight" },
  { accessType: "write", recordType: "Weight" },
  { accessType: "read", recordType: "WheelchairPushes" },
  { accessType: "write", recordType: "WheelchairPushes" },
];
